---
- name: install packages
  with_items: "{{ packages }}"
  package:
    name: "{{ item.name }}"
    state: latest

- name: enable buildbot
  template:
    src: buildbot.j2
    dest: /etc/rc.conf.d/buildbot

- name: enable buildbot worker
  template:
    src: buildbot_worker.j2
    dest: /etc/rc.conf.d/buildbot_worker

- name: create buildbot master
  command: buildbot create-master /root/master creates=/root/master

- name: create buildbot worker
  command: buildbot-worker create-worker /root/worker localhost {{ worker_name }} {{ worker_password }} creates=/root/worker

- name: configure buildbot
  template:
    src: master.cfg.j2
    dest: /root/master/master.cfg

- name: start buildbot
  service:
    name: buildbot
    state: started
    enabled: yes

- name: start buildbot-worker
  service:
    name: buildbot-worker
    state: started
    enabled: yes

